import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsappButton from "@/components/WhatsappButton";

const RobotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Kert S.A.S | Innovación, Estilo y Resistencia en Maletería al Por Mayor",
  description: "Generated by create next app",
  // Acá agrega el titulo de la pagina y la meta descripcion, como esta en el layout se va a repetir en todas las paginas
  // Si queres cambiarlo en una pagina en especifico, podes hacerlo en el archivo de la pagina
  // Para una mejor puntuacion de SEO es mejor tener un titulo y una descripcion unica en cada pagina
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${RobotoFont.variable} antialiased mt-[68px]`}>
        <Navbar />
        
          {children}
        
        <Footer />
        <div>
          <WhatsappButton
            message="¡Hola! Quisiera más información."
            phoneNumber="12345789"
          /></div>
      </body>
    </html>
  );
}
